logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%clr(%5level)] [%thread] %clr(%logger{20}.%M){cyan}\(%F:%line\) - %msg%n'

# 根路径配置
server:
  address: 0.0.0.0
  port: 17333
  servlet:
    context-path: /

simulator:
  port: 17313
  nodePath: C:/Program Files/nodejs/node.exe
  chromePath: D:\Project\puppeteer-start\puppeteer\chrome\win64-123.0.6312.122\chrome-win64\chrome.exe
  workingPath: D:\Project\ai-simulator
  headless: false
  simulators:
    - alibaba
    - baidu
    - tencent
    - openai
    - google


net:
  id: netConfig
  protocol-location: protocol.xml
  code-languages: 0
  fold-protocol: true